// AUTO-GENERATED by generate_website_experiments.js
// DO NOT EDIT - regenerate via: node workspace/tools/generate_website_experiments.js

/**
 * Test Statistics - Calculated from Actual Test Results (Canonical Source Preferred)
 * ======================================================
 * 
 * Generated: 2025-11-13T03:32:02.017Z
 * Source: workspace/results/test_registry_canonical.json
 * 
 * Semantics:
 * - Executed-only: SKIP-designated tests are excluded from denominators
 * - passRate = passed / executed
 * - When available, values are sourced from test_registry_canonical.json
 *   to ensure website matches uploads and pre-commit validation
 */

export const testStatistics = {
  /** Total number of tests across all tiers (executed-only; SKIP excluded) */
  total: 105,
  
  /** Number of tests currently passing */
  passing: 105,
  
  /** Number of tests failing */
  failing: 0,
  
  /** Pass rate as percentage string (e.g., "91.3%") */
  passRate: '100.0%',
  
  /** Breakdown by tier (executed-only; no tier can have passing > total) */
  byTier: {
  "1": {
    "total": 17,
    "passing": 17
  },
  "2": {
    "total": 25,
    "passing": 25
  },
  "3": {
    "total": 11,
    "passing": 11
  },
  "4": {
    "total": 14,
    "passing": 14
  },
  "5": {
    "total": 21,
    "passing": 21
  },
  "6": {
    "total": 12,
    "passing": 12
  },
  "7": {
    "total": 5,
    "passing": 5
  }
},
  
  /** ISO timestamp of when this was generated */
  generatedAt: '2025-11-13T03:32:02.017Z'
} as const;

/**
 * Formatted pass rate for display
 * Example: "91.3% Tests Pass"
 */
export function formatPassRate(): string {
  return `${testStatistics.passRate} Tests Pass`;
}

/**
 * Human-readable summary
 * Example: "95 of 104 tests passing"
 */
  export function formatSummary(): string {
    return `${testStatistics.passing} of ${testStatistics.total} executed tests passing`;
}
