#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# © 2025 Emergent Physics Lab. All rights reserved.
# Licensed under CC BY-NC-ND 4.0 (Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International).
# Non-commercial use with attribution only; no distribution of modified material; commercial use requires prior written permission.
# SPDX-License-Identifier: CC-BY-NC-ND-4.0

"""
Install Git Pre-Commit Hook
===========================

Creates/overwrites .git/hooks/pre-commit to invoke the unified pre-commit suite.
Safe to run multiple times (idempotent). This is a LOCAL convenience; the hook
file is NOT tracked in git.

Usage:
    python workspace/tools/install_pre_commit_hook.py

After installation, every `git commit` will run:
  python workspace/tools/run_pre_commit_suite.py

Override behavior with environment variables (see run_pre_commit_suite.py docstring).
"""
from __future__ import annotations

import os
import stat
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
HOOKS_DIR = REPO_ROOT / '.git' / 'hooks'
HOOK_FILE = HOOKS_DIR / 'pre-commit'

HOOK_CONTENT = """#!/usr/bin/env bash
# Auto-generated by install_pre_commit_hook.py
# Runs LFM pre-commit suite (IP protection + tests)

# Use repo root
REPO_ROOT="$(git rev-parse --show-toplevel)"
PY=\\"$REPO_ROOT/.venv/Scripts/python.exe\\"
SCRIPT=\\"$REPO_ROOT/workspace/tools/run_pre_commit_suite.py\\"

if [ ! -x "$PY" ]; then
  echo "Python virtual env not found at $PY" >&2
  exit 1
fi

if [ ! -f "$SCRIPT" ]; then
  echo "Pre-commit suite script missing: $SCRIPT" >&2
  exit 1
fi

# Run suite
"$PY" "$SCRIPT"
rc=$?
if [ $rc -ne 0 ]; then
  echo "Pre-commit suite failed (exit $rc). Aborting commit." >&2
  exit $rc
fi

exit 0
"""


def main() -> int:
    if not HOOKS_DIR.exists():
        print(f"Creating hooks directory: {HOOKS_DIR}")
        HOOKS_DIR.mkdir(parents=True, exist_ok=True)
    HOOK_FILE.write_text(HOOK_CONTENT, encoding='utf-8')
    # Make executable
    mode = HOOK_FILE.stat().st_mode
    HOOK_FILE.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"Installed pre-commit hook -> {HOOK_FILE}")
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
